<?php
// This file is part of Moodle - https://moodle.org/.
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

namespace local_edc_exporter\local\credential;

/**
 * Checks that the official JSON has minimum data before marking it as generated.
 *
 * This validation does not replace external validators. It only helps detect
 * clear issues inside Moodle before creating the downloadable file.
 *
 * @package    local_edc_exporter
 * @copyright  2026 Skills Divers
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class schema_validator {
    /**
     * Checks important fields in the official JSON.
     *
     * @param array $payload Official JSON as a PHP array.
     * @return array List of errors found. If empty, the JSON can be stored as generated.
     */
    public static function validate(array $payload): array {
        // List where all detected issues are collected.
        $errors = [];

        if (empty($payload['credential']) || !is_array($payload['credential'])) {
            return ['Missing root credential object.'];
        }

        // Main JSON section. Internal fields are checked from this point.
        $credential = $payload['credential'];

        // Basic fields required by any credential generated by this plugin.
        foreach (['id', 'type', 'credentialSchema', 'credentialSubject', 'issuanceDate', 'issued'] as $field) {
            if (empty($credential[$field])) {
                $errors[] = get_string('validationmissingcredentialfield', 'local_edc_exporter', $field);
            }
        }

        // Data for the person receiving the credential.
        $cs = $credential['credentialSubject'] ?? null;
        if (empty($cs) || !is_array($cs)) {
            // Stop here because the remaining checks depend on the subject.
            $errors[] = 'Missing credentialSubject.';
            return $errors;
        }

        if (empty($cs['fullName'])) {
            $errors[] = 'Missing learner fullName.';
        }

        if (empty($cs['contactPoint'][0]['emailAddress'][0]['id'])) {
            $errors[] = 'Missing learner email (contactPoint.emailAddress.id).';
        }

        // Achievement recognised in the credential, usually the completed course.
        $claim = $cs['hasClaim'][0] ?? null;
        if (empty($claim)) {
            // HasClaim contains the LearningAchievement; without it there is no exportable achievement.
            $errors[] = 'Missing hasClaim[0].';
            return $errors;
        }

        if (empty($claim['title'])) {
            $errors[] = 'Missing hasClaim[0].title.';
        }

        // Organisation that awards the achievement.
        $awardedby = $claim['awardedBy'] ?? null;
        if (empty($awardedby)) {
            $errors[] = 'Missing hasClaim[0].awardedBy.';
        } else {
            if (empty($awardedby['awardingBody'][0]['legalName'])) {
                $errors[] = 'Missing awardingBody[0].legalName.';
            }
        }

        // Course or achievement description: title, hours, and learning outcomes.
        $specifiedby = $claim['specifiedBy'] ?? null;
        if (empty($specifiedby)) {
            $errors[] = 'Missing hasClaim[0].specifiedBy.';
        } else {
            if (empty($specifiedby['title'])) {
                $errors[] = 'Missing specifiedBy.title.';
            }
            // Learning outcomes. Although the text says "Warning", this is stored
            // as an error and blocks generation because that is how the plugin currently works.
            if (empty($specifiedby['learningOutcome'])) {
                $errors[] = 'Warning: specifiedBy.learningOutcome is empty. '
                    . 'Set the "credential_learning_outcomes" custom field on the course.';
            }
            // Course workload. It comes from credential_workload_hours or edc_hours.
            if (empty($specifiedby['volumeOfLearning'])) {
                $errors[] = 'Missing specifiedBy.volumeOfLearning. '
                    . 'Set the "credential_workload_hours" custom field on the course.';
            }
        }

        // Data that helps display the credential in external tools.
        $dp = $credential['displayParameter'] ?? null;
        if (empty($dp)) {
            $errors[] = 'Missing displayParameter.';
        } else {
            if (empty($dp['language'])) {
                $errors[] = 'Missing displayParameter.language.';
            }
        }

        return $errors;
    }
}
